### ISSUE TITLE
Remove logging in production mode

### ISSUE THREAD

**Issue by amanjagdev** [amanjagdev/auto-log#2]
All these logs must not be mentioned if the environment is set to PRODUCTION.
i.e No logging should be done in production mode

**Comment by MathurAditya724** [comment]
Hey, can you assign this to me?

**Comment by amanjagdev** [comment]
Ya sure... you can work on it...
Just make sure to test your code well 👍

**Comment by amanjagdev** [comment]
The issue has been resolved, by PR #3
